### ISSUE TITLE
NMP Package not installing

### ISSUE THREAD

**Issue by davidbudnick** [NickNaso/magick-cli#12]
There is an error when running any version of Magick-cli

![image](https://user-images.githubusercontent.com/18271248/42299037-88079cbe-7fce-11e8-84a7-31636ff2be4f.png)

**Comment by NickNaso** [comment]
Hi @davidbudnick,
it' seems that you don't have the python executable command set on your system. 
You are in windows and to fix this problem you can use *windows-build-tools* [https://www.npmjs.com/package/windows-build-tools](https://www.npmjs.com/package/windows-build-tools) and if after its installation you will obtain the same error take a look at this guide [https://www.npmjs.com/package/windows-build-tools#support--help](https://www.npmjs.com/package/windows-build-tools#support--help)

**Comment by davidbudnick** [comment]
Thanks, Nick for the fast reply!

I installed the windows-build-tools as you suggested, that removed the python problem when installing. There are a few more issues that happend when installing as you see in the screenshot below:

![image](https://user-images.githubusercontent.com/18271248/42302541-2e386566-7fe1-11e8-974f-98748cd7ea56.png)

I did try to run it on ubuntu too, and I am having simliar issues. I attached a screenshot of the problems on ubutnu: (I would rather run in on ubutnu)
![image](https://user-images.githubusercontent.com/18271248/42302699-10c29d02-7fe2-11e8-87bc-e6e0ae8c8a33.png)

When this is working I have a ImageMagick I would want to rewrite in Node.Js in your API.
Here is the an example of the line I am trying to rewrite:
`convert t.png \( IMG_8433.JPG -resize 857x547 -chop 0x25 \) -geometry +227+248 -composite IMG_8433.pdf`

If I understand how your API works then I should be able to write it like this:
![image](https://user-images.githubusercontent.com/18271248/42302808-d2c89492-7fe2-11e8-9d73-fa46b98b3354.png)



Is this possible in the API?

Thanks!
David Budnick

**Comment by NickNaso** [comment]
Hi @davidbudnick,
which version of ImageMagick are you using? To retry the information you can use
`magick --version` or `convert --version`

**Comment by davidbudnick** [comment]
Here is the version of convert I am using:
![image](https://user-images.githubusercontent.com/18271248/42325739-bf6bb77c-802c-11e8-8d54-48edaeaff940.png)

**Comment by NickNaso** [comment]
Hi @davidbudnick, 
this is the problem you need to update at version 7.0.1 or above because *magick-cli* use C/C++ API added starting from this version.

https://www.npmjs.com/package/magick-cli#at-the-moment-magickcli-is-fully-compatible-with-imagemagick-from-version-701-to-708

Probably you have the same problem on windows.

Keep me updated about this.

**Comment by davidbudnick** [comment]
Ok, I updated to the newest version of ImageMagick and I am installing having errors with the package.

![image](https://user-images.githubusercontent.com/18271248/42353595-1fb0cbc2-8087-11e8-9a00-d48d43a99a4c.png)

**Comment by NickNaso** [comment]
Hi @davidbudnick,
your ubuntu system need of *pkg-config*
`sudo apt-get update && sudo apt-get install pkgconfig`
In general you need to continue experimenting problems because the native part of the module need to be compiled so I advice you to install all necessary packages to accomplish at this task:
`sudo apt-get update && sudo apt-get install build-essential`
Try this and please send a feedback.

**Comment by davidbudnick** [comment]
Hi Nick, 
I am still having the issue with installing from npm.

Not sure what to do next. I also updated my systems packages nothing is working ☹️ 

![image](https://user-images.githubusercontent.com/18271248/42425799-4bcdd166-82e7-11e8-8f6c-ee307b9aabc7.png)

**Comment by NickNaso** [comment]
Hi @davidbudnick ,
sorry  I did a mistake on my previous suggestion, you need to install `pkg-config` so the right command is `sudo apt-get install pkg-config`.  After that you need to check if your imagemagick version is  7.0.1 or above. If you continue to be have problems try to install this library:
`sudo apt-get install libmagick++-dev`
Hope that this info help you and as always send me a feedback.

**Comment by NickNaso** [comment]
@davidbudnick did you try what I proposed?

**Comment by davidbudnick** [comment]
Hey Nick,
It worked! Thanks so much for the help fixing your API.

I would like to use your API to convert my image magick command line function to Node.JS so I can run it on a google cloud function. (https://cloud.google.com/functions/docs/tutorials/imagemagick)

Here is an example of the line I am trying to rewrite:
`convert t.png \( IMG_8433.JPG -resize 857x547 -chop 0x25 \) -geometry +227+248 -composite IMG_8433.pdf`

If your API could work with this it could be an added feature to the API, lots more people would want to download it! 😄 

Any advice would help!

Thanks,
David Budnick

**Comment by NickNaso** [comment]
Hi @davidbudnick,
I'm happy to hear this. I looked at the example you reported above, where ImageMagick has been called through `exec` and this means that you have a working installation of ImageMagick. I don't now if you can launch `npm install` on post deploy / upload your application to google. In this case you can try to use `magick-cli` otherwise you need to wait a little because I need to modify all the build process for the add-on. Please try and post here the error you will receive, so I can understand better how to move to increase the features of `magick-cli`.

**Comment by NickNaso** [comment]
Hi @davidbudnick,
any useful info to give to me? Did you try to install the module on the cloud?

**Comment by weslley-campos** [comment]
@NickNaso Any solution for windows? I have the same problem but on windows.

**Comment by weslley-campos** [comment]
I do installed https://www.npmjs.com/package/windows-build-tools, but don't work.

**Comment by weslley-campos** [comment]
https://user-images.githubusercontent.com/29134909/43734265-8e4c943e-998d-11e8-8ec2-7548b425d56e.png

Log image...

**Comment by weslley-campos** [comment]
![image](https://user-images.githubusercontent.com/29134909/43734356-d2ebc2c2-998d-11e8-994c-d20c21bc7bbf.png)

**Comment by NickNaso** [comment]
Hi @weslley-campos ,
sorry for your problem to help me to debug better it I need that you check for me which version of python you have installed on you pc:
`> python --version` 
Then you need to go  inside the folder 
`node_modules/magick-cli` and digit `python magick-cli-path.py`
and report what you obtain.

I think that you need to install ImageMagick on your windows. You can do that following this link **[Image Magick Installer](https://www.imagemagick.org/download/binaries/ImageMagick-7.0.8-9-Q16-x64-dll.exe)**.
After the installation  a key will be create on the windows registry:
`HKEY_LOCAL_MACHINE/SOFTWARE/ImageMagick/Current/LibPath`
Usually if ImageMagick is not installed you obtain the error you reported because the python script try to retrieve a registry key that does not exists.

I hope that my informations help you to solve the problem. Please keep me updated about that.

**Comment by weslley-campos** [comment]
PS C:\Users\Weslley\Desktop\MagickCLI> python --version
Python 2.7.14

I can't access the folder, because of the error don't download.

Ambient variables: 
![image](https://user-images.githubusercontent.com/29134909/43743909-13624c84-99ae-11e8-93a6-89e601cafa5d.png)

Regedit:
![image](https://user-images.githubusercontent.com/29134909/43743947-3d0ac016-99ae-11e8-8058-79963697ae28.png)

I follow all the steps for installation. And other packages are with the same problem.

**Comment by NickNaso** [comment]
Try this:
```
> npm i magick-cli --MAGICK="C:\Program Files\ImageMagick-7.0.8-Q16"
```

**Comment by weslley-campos** [comment]
Same wrong!
![image](https://user-images.githubusercontent.com/29134909/43744994-f5dadd20-99b2-11e8-82eb-feab156f45e7.png)

the error is in node-gyp, but configured right, using this tutorial https://github.com/nodejs/node-gyp, the prerequisite.

**Comment by NickNaso** [comment]
The problem is in pyhton. 
Try 
```npm config set python python2.7```
and if it does not work
```npm config set python /path/to/executable/python2.7 ```

**Comment by weslley-campos** [comment]
Corrected any error with Python, reinstall in root of the system and link with environment variables.
But continue error.

![image](https://user-images.githubusercontent.com/29134909/43746150-e9e11006-99b8-11e8-87d3-9d56c41d1034.png)

**Comment by NickNaso** [comment]
Hi @weslley-campos,
the problem is in your ImageMagick installation you have to check **Install development headers and libraries for  and C++**.  
![setup](https://user-images.githubusercontent.com/387506/43749089-ef50e82e-99f2-11e8-8138-72fb0a230243.png)

**Comment by weslley-campos** [comment]
Hey man, very very thanks. The problem has gone to fix it.
